---

  - name: install python libs
    yum:
      name: ['libxml2', 'libxml2-devel', 'libxslt', 'libxslt-devel', 'python2', 'python-pip']
      state: installed

  - name: Upgrade pip
    pip:
      name: pip
      state: latest

  - name: Install lxml
    pip:
      name: lxml
      state: present

  - name: download pet
    maven_artifact:
      group_id:  '{{ group_id }}'
      artifact_id:  '{{ artifact_id }}'
      extension: '{{ artifact_extension }}'
      version:  '{{ build_version }}'
      repository_url: '{{ repository_url }}'
      username: '{{ user }}'
      password: '{{ password }}'
      dest: '{{ petclinic_path }}'
      mode: '744'

  - name: Make petclinic service
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "644"
    with_items:
      - { src: 'petclinic.service.j2', dest: '/etc/systemd/system/petclinic.service' }
      - { src: 'start_petclinic.sh.j2', dest: '/home/{{ petclinic_user }}/start_petclinic.sh' }

  - name: start petclinic
    systemd:
      name: petclinic
      state: started
      enabled: yes

...
