---

- hosts: default
  become: yes
  become_method: sudo
  gather_facts: no
  tags: Web
  roles:
    - { role: pre_req }
    - { role: java_role }
    - { role: nginx_role }
    - { role: deploy_petclinic }

...
