petclinic_path      : /tmp/petclinic.jar
nexus_url           :
nexus_port          : 8081

repo                : repository/maven-snapshots
jar_file            : org/springframework/samples/spring-petclinic/2.3.1b.BUILD-SNAPSHOT/spring-petclinic-2.3.1b.BUILD-20200819.064315-11.jar
petclinic_jar_url   : http://{{ nexus_url }}:{{ nexus_port }}/{{ repo }}/{{ jar_file }}
user                : admin
password            : !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33396665366530346631343939313662383138333532356539363437613064316332373864346438
          3039356238373530376231313064373230343437306235620a346530636437353633306632316632
          65363237356439643466313034313730333635376133353534363638363664393365313033306363
          6664393063663535360a306230343436383238383232656330386164613536336438393162623564
          3239
petclinic_user      : dzakharchenko
petclinic_arguments : --spring.profiles.active=mysql --spring.jpa.hibernate.ddl-auto=update --spring.datasource.url=jdbc:mysql://{{ mysql_ip }}:3306/petclinic?useSSL=false --spring.datasource.username={{ mysql_user }} --spring.datasource.password={{ mysql_pass }} --spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
group_id           : org.springframework.samples
artifact_id        : spring-petclinic
artifact_extension : jar
build_version      : 2.3.1b.BUILD-SNAPSHOT
repository_url     : http://{{ nexus_url }}:{{ nexus_port }}/{{ repo }}/
version_id : 'latest'
mysql_user : 'petclinic'
mysql_port : '3306'
mysql_db_name : 'petclinic'
profile : 'mysql'
mysql_ip_secret : mysql_ip_dz
mysql_pass : DB_PASS
