---

  - name: yum Update
    yum: update_cache=yes

  - name: Create a directory
    tags: java
    file:
      path: '{{ item }}'
      state: directory
      mode: '0755'
    with_items:
      - ["/tmp/soft"]

  - name: Download java
    get_url:
      url: '{{ java_url }}'
      dest: /tmp/soft/{{ jdk_tar }}

  - name: Unarchive java
    tags: tar
    unarchive:
      src:     /tmp/soft/{{ jdk_tar }}
      dest:    /usr/bin/
      remote_src: yes
      extra_opts:
      - --transform
      - s/^{{ java_tar_dir }}/{{ java_dir }}/

  - name: Correct java version selected
    alternatives:
      name: java
      path: /usr/bin/{{ java_dir }}/bin/java
      link: /usr/bin/java
      priority: 100

  # - name: Set JAVA_HOME and add to PATH
  #   shell: |
  #     export JAVA_HOME="/usr/bin/{{ java_dir }}"
  #     export PATH="$PATH:$JAVA_HOME/bin"
  #     echo "JAVA_HOME=$JAVA_HOME" >> /etc/environment
  #     source /etc/environment

  #     alternatives --install /usr/bin/java java /usr/bin/{{ java_dir }}/bin/java 100
  #     echo "1" | alternatives --config java
  #     # alternatives --install /usr/bin/jar jar /usr/bin/java/{{ java_dir }}/bin/jar 2
  #     # alternatives --install /usr/bin/javac javac /usr/bin/java/{{ java_dir }}/bin/javac 2
  #     # alternatives --set jar /usr/bin/java/{{ java_dir }}/bin/jar
  #     # alternatives --set javac /usr/bin/java/{{ java_dir }}/bin/javac
  #     export JRE_HOME=/usr/bin/java/{{ java_dir }}/jre

  - shell: java -version && echo -e "\n$JAVA_HOME"
    register: java_env

  - debug:
      msg:
      - "----Java version----\n {{ java_env }}"

...
