jenkins_home                      : /var/lib/jenkins
# public_key                        : "{{ lookup('file', '{{ path.stdout }}/{{ ssh_key }}.pub') }}"
# private_key                       : "{{ lookup('file', '{{ path.stdout }}/{{ ssh_key }}') }}"
public_key                        : "{{ lookup('file', '/Users/dzakharchenko/.ssh/github.pub') }}"
private_key                       : "{{ lookup('file', '/Users/dzakharchenko/.ssh/github') }}"
jenkins_user                      : jenkins
jenkins_pass                      : pass
jenkins_fullName                  : Jenkins_Admin
gitName                           : jenkins
gitEmail                          : jenkins@example.com
gitUrl                            : git@github.com:Yakushi12/spring-petclinic.git
credentials                       : GH_private_key
branch                            : '*/main'
targetBranch                      : main
jobName                           : deploy_to_nexus
mavenVersion                      : 3.6.3
mavenName                         : Maven
mavenRepo                         : maven-snapshots
jenkinsSSHcredentials_description : private key for GitHub
jenkinsKey_id                     : nexus-cred
jenkinsKey_description            : Login to Nexus3 OSS
jenkinsKey_user                   : admin
jenkinsKey_pass                   : password
