# job - Build image n run container
docker_volume                     : jenkins_home
docker_image_name                 : jenkins-docker
docker_container_name             : jenkins
# job - Build Jenkins job, file - 03.2-deploy-to-nexus-job.groovy.j2
jobName                           : deploy_nexus
jenkins_token                     : 11517e4ae0308056e4ea15d6d179f0f7f9
# file - 00-basic-security.groovy.j2
jenkins_user                      : jenkins
jenkins_pass                      : pass
jenkins_fullName                  : Jenkins_Admin
public_key                        : "{{ lookup('file', '/Users/dzakharchenko/.ssh/github.pub') }}"
# file - 01-global-settings.groovy.j2
gitName                           : jenkins
gitEmail                          : jenkins@example.com
# file - 02-add-credentials.groovy.j2
credentials                       : GH_private_key
jenkinsSSHcredentials_description : 'private key for GitHub'
private_key                       : "{{ lookup('file', '/Users/dzakharchenko/.ssh/github') }}"
jenkinsKey_id                     : nexus-cred
jenkinsKey_description            : 'Login to Nexus3 OSS'
jenkinsKey_user                   : admin
jenkinsKey_pass                   : password
jenkinsFile_id                    : 'gcp_service_acc_cred'
jenkinsFile_description           : 'Service account json Key'
jenkinsFile_name                  : 'account.json'
valut_pass_id                     : 'pass'
valut_pass_description            : 'password for ansible vault'
valut_pass_name                   : 'pass'
valut_pass                        : "{{ lookup('file', '/Users/dzakharchenko/vpass') }}"
# file - 04-maven.groovy.j2
mavenVersion                      : 3.6.3
mavenName                         : Maven
# files - Jenkinsfiles
nexus_ip_secret                   : "nexus_ip_dz"
gitCIurl                          : git@github.com:Yakushi12/jenkins-automatization-docker.git
gitUrl                            : git@github.com:Yakushi12/spring-petclinic.git
branch                            : '*/main'
targetBranch                      : main
service_acc_key                   : service_acc_key
jenkins_home                      : /var/lib/jenkins
