# job - Build image n run container
docker_volume                     : jenkins_home
docker_image_name                 : jenkins-docker
docker_container_name             : jenkins
# file - 00-basic-security.groovy.j2
jenkins_fullName                  : Jenkins_Admin
# file - 01-global-settings.groovy.j2
git_config_Name                   : jenkins
git_config_Email                  : jenkins@example.com
NumExecutors                      : 3
# file - 02-add-credentials.groovy.j2
github_ssh_credentials            : GH_private_key
github_ssh_cred_description       : 'private key for GitHub'
Nexus_login_creds_id              : nexus-cred
Nexus_login_creds_description     : 'Login to Nexus3 OSS'
ansible_valut_pass_id             : 'pass'
ansible_valut_pass_description    : 'password for ansible vault'
ansible_valut_pass_name           : 'pass'
# files 03-*
branch                            : '*/main'
git_pipelines_url                 : git@github.com:Yakushi12/jenkins-pipelines.git
# file - 04-maven.groovy.j2
mavenVersion                      : 3.6.3
mavenName                         : Maven
