# job - Build image n run container
docker_volume                     : jenkins_home
docker_image_name                 : jenkins-docker
docker_container_name             : jenkins
# file - 00-basic-security.groovy.j2
jenkins_user                      : jenkins
jenkins_pass                      : !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39633439313661333630656133636466666362393463396633616430666534623134376136653364
          3334623639326432623064666237396533363631626262330a663730373035636634633539343861
          32353863646463653138396235333334323031373230346264376636613462386535643762323230
          6234663165616430330a653736643764616263343330653136313162643535333138396366376461
          6534
jenkins_fullName                  : Jenkins_Admin
public_key                        : "{{ lookup('file', '/Users/dzakharchenko/.ssh/github.pub') }}"
# file - 01-global-settings.groovy.j2
gitName                           : jenkins
gitEmail                          : jenkins@example.com
# file - 02-add-credentials.groovy.j2
credentials                       : GH_private_key
jenkinsSSHcredentials_description : 'private key for GitHub'
private_key                       : "{{ lookup('file', '/Users/dzakharchenko/.ssh/github') }}"
jenkinsKey_id                     : nexus-cred
jenkinsKey_description            : 'Login to Nexus3 OSS'
jenkinsKey_user                   : admin
jenkinsKey_pass                   : password
jenkinsFile_id                    : 'gcp_service_acc_cred'
jenkinsFile_description           : 'Service account json Key'
jenkinsFile_name                  : 'account.json'
valut_pass_id                     : 'pass'
valut_pass_description            : 'password for ansible vault'
valut_pass_name                   : 'pass'
valut_pass                        : "{{ lookup('file', '/Users/dzakharchenko/vpass') }}"
# files 03-*, task - build_job.yml
branch                            : '*/main'
jobName                           : 'pack and deploy artefact'
jenkins_token                     : 11517e4ae0308056e4ea15d6d179f0f7f9
jenkins_port                      : 8080
git_pipelines_url                 : git@github.com:Yakushi12/jenkins-pipelines.git
# file - 04-maven.groovy.j2
mavenVersion                      : 3.6.3
mavenName                         : Maven
