---

- hosts: default
  become: true
  gather_facts: no
  roles:
    - { role: docker, tags: jenkins-install }
    - { role: jenkins_role }
  vars:
    proxy_port: '{{ jenkins_port }}'

- hosts: Jenkins
  become: true
  gather_facts: no
  roles:
    - { role: jenkins_role }
...
