---

- hosts: default
  become: true
  gather_facts: no
  roles:
    - { role: nexus_role }

- hosts: localhost
  gather_facts: no
  tags: nexus-configure
  tasks:
    - name: Wait port 22
      wait_for:
        port: 22
        search_regex: OpenSSH
        delay: 10
        sleep: 3
        host: "{{ nexus_url }}"
        timeout: 40

- hosts: Nexus
  become: true
  gather_facts: no
  roles:
    - { role: nexus_role }

...
