---

  - name: update yum
    yum: update_cache=yes

  - name: install wget n jdk
    yum:
      name: "{{ packages }}"
      state: installed

  - name: create "nexus" group
    group:
      name: nexus

  - name: create "nexus" user
    user:
      name: nexus
      group: nexus

  - name: download nexus
    get_url: url={{nexus_download_url}} dest={{nexus_download_dest}}
    register: nexus_download

  - name: create {{nexus_extracted_dir}} directory
    file: path={{nexus_extracted_dir}} state=directory
    when: nexus_download.changed

  - name: extract nexus to {{nexus_extracted_dir}}
    command: tar xzf {{nexus_download_dest}} -C {{nexus_extracted_dir}} --strip-components=1
    when: nexus_download.changed

  - name: move nexus to {{nexus_dir}} directory
    command: cp -a {{nexus_extracted_dir}}/. {{nexus_dir}}
    when: nexus_download.changed

  - name: remove {{nexus_extracted_dir}} directory
    command: rm -rf {{nexus_extracted_dir}}
    when: nexus_download.changed

  - name: make '{{nexus_dir}}' directory property of "nexus" user/group
    file:
      path: '{{nexus_dir}}'
      group: nexus
      owner: nexus
      recurse: true

  - name: make nexus runned by "nexus" user
    lineinfile:
      dest: '{{nexus_dir}}/bin/nexus'
      regexp: "#RUN_AS_USER="
      line: "RUN_AS_USER=nexus"
      backrefs: true

  - name: set NEXUS_HOME
    lineinfile:
      dest: '{{nexus_dir}}/bin/nexus'
      regexp: "^NEXUS_HOME"
      line: "NEXUS_HOME={{nexus_dir}}"
      backrefs: true

  - name: create nexus piddir
    file:
      path: /var/run/nexus
      state: directory
      group: nexus
      owner: nexus

  - name: set nexus pidir
    lineinfile:
      dest: '{{nexus_dir}}/bin/nexus'
      regexp: "^#PIDDIR="
      line: "PIDDIR=/var/run/nexus"
      backrefs: true

  - name: create symbolic links to /etc/init.d/nexus
    file:
      src: '{{nexus_dir}}/bin/nexus'
      dest: /etc/init.d/nexus
      state: link

  - name: configure runlevel links for nexus
    command: chkconfig nexus on

  - name: start nexus
    systemd: name=nexus state=started

  - name: sleep for 30 seconds and continue with play
    wait_for:
      timeout: 30

...
