---

  - name: Check Hostname
    command: hostname
    register: hname
    tags: always

  - debug: msg="{{ hname.stdout }}"
    tags: always

  - import_tasks: install_nexus.yml
    tags: nexus-install

  - import_tasks: configure_nexus.yml
    tags: nexus-configure

...
