---

  - name: Check Hostname
    command: hostname
    register: hname

  - debug: msg="{{ hname.stdout }}"

  - name: yum Update
    yum: update_cache=yes

  - name: Create a directory
    tags: java
    file:
      path: '{{ item }}'
      state: directory
      mode: '0755'
    with_items:
      - ["/tmp/soft"]

  - name: Download java
    get_url:
      url: '{{ java_url }}'
      dest: /tmp/soft/{{ jdk_tar }}

  - name: Unarchive java
    tags: tar
    unarchive:
      src:     /tmp/soft/{{ jdk_tar }}
      dest:    /usr/bin/
      remote_src: yes
      extra_opts:
      - --transform
      - s/^{{ java_tar_dir }}/{{ java_dir }}/

  - name: Correct java version selected
    alternatives:
      name: java
      path: /usr/bin/{{ java_dir }}/bin/java
      link: /usr/bin/java
      priority: 100

  - shell: java -version && echo -e "\n$JAVA_HOME"
    register: java_env

  - debug:
      msg:
      - "----Java version----\n {{ java_env }}"

...
