---

  - name: Check Hostname
    command: hostname
    register: hname

  - debug: msg="{{ hname.stdout }}"

  - name: yum Update
    yum: update_cache=yes

  - name: Downoload packages
    yum:
      name: "{{ packages }}"
      state: latest

  - name: Configuring docker-ce repo
    get_url:
      url: "{{ docker_ce_url }}"
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644

  - name: Upgrade pip
    pip:
      name: pip
      state: latest

  - name: Install docker-ce
    yum:
      name: docker-ce
      state: present

  - name: Install docker-py
    pip:
      name: docker-py
      state: present

  - name: Start n enable docker
    systemd:
      name: docker
      state: started
      enabled: true

  - name: Add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: true

...
