---

  - name: Check that Jenkins is ready
    uri:
      url: "http://{{ jenkins_url }}:{{ jenkins_port }}"
      user: "{{ admin_username }}"
      password: "{{ admin_password }}"
      method: "GET"
      force_basic_auth: "yes"
      return_content: "yes"
      status_code: ['200', '403']
    register: "this"
    until: "'Dashboard' in this.content"
    retries: 15
    delay: 5

...
