---

  - name: Set init scripts to Docker directory
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      mode: '0744'

    with_items:
      - { src: '00-basic-security.groovy.j2', dest: './Docker/scripts/00-basic-security.groovy' }
      - { src: '01-global-settings.groovy.j2', dest: './Docker/scripts/01-global-settings.groovy' }
      - { src: '02-add-credentials.groovy.j2', dest: './Docker/scripts/02-add-credentials.groovy' }
      - { src: '03.1-packer-build-job.groovy.j2', dest: './Docker/scripts/03.1-packer-build-job.groovy' }
      - { src: '03.2-deploy-to-nexus-job.groovy.j2', dest: './Docker/scripts/03.2-deploy-to-nexus-job.groovy' }
      - { src: '04-maven.groovy.j2', dest: './Docker/scripts/04-maven.groovy' }
      - { src: 'Jenkinsfile-03.1.j2', dest: './Docker/scripts/Jenkinsfile-03.1' }
      - { src: 'Jenkinsfile-03.2.j2', dest: './Docker/scripts/Jenkinsfile-03.2' }
      - { src: 'Jenkinsfile-03.3.j2', dest: './Docker/scripts/Jenkinsfile-03.3' }
      - { src: '03.3-terraform-job.groovy.j2', dest: './Docker/scripts/03.3-terraform-job.groovy' }

  - name: Run docker container
    shell: |
      docker run -d --restart unless-stopped --privileged --name {{ docker_container_name }} -p 0.0.0.0:8080:8080 -p 0.0.0.0:50000:50000 -v /home/{{ ansible_user }}/{{ docker_volume }}:/var/{{ docker_volume }} {{ docker_image_name }}
      docker cp Docker/scripts/. {{ docker_container_name }}:/usr/share/jenkins/ref/init.groovy.d/
      docker restart {{ docker_container_name }}
  - name: Change Jenkins-home ownership, group and permissions
    file:
      path: /home/{{ ansible_user }}/{{ docker_volume }}
      mode: "1755"
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      recurse: yes

...
