---

  - name: Creates Docker directory
    file:
      path: ./Docker/scripts/
      state: directory
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      directory_mode: yes

  - name: Set init scripts to Docker directory
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      mode: '0744'
    with_items:
      - { src: 'jenkins-plugins', dest: './Docker/jenkins-plugins' }
      - { src: 'Dockerfile.j2', dest: './Docker/Dockerfile' }
      - { src: '00-basic-security.groovy.j2', dest: './Docker/scripts/00-basic-security.groovy' }
      - { src: '01-global-settings.groovy.j2', dest: './Docker/scripts/01-global-settings.groovy' }
      - { src: '02-add-credentials.groovy.j2', dest: './Docker/scripts/02-add-credentials.groovy' }
      - { src: '03.1-pack-and-deploy.groovy.j2', dest: './Docker/scripts/03.1-pack-and-deploy.groovy' }
      - { src: '03.2-packer-build-job.groovy.j2', dest: './Docker/scripts/03.2-packer-build-job.groovy' }
      - { src: '03.3-terraform-job.groovy.j2', dest: './Docker/scripts/03.3-terraform-job.groovy' }
      - { src: '04-maven.groovy.j2', dest: './Docker/scripts/04-maven.groovy' }

  - name: Build docker image and Run docker container
    shell: |
      docker build -t {{ docker_image_name }} ./Docker/.
      docker run -d --restart unless-stopped --privileged --name {{ docker_container_name }} -p 0.0.0.0:8080:8080 -p 0.0.0.0:50000:50000 -v /home/{{ ansible_user }}/{{ docker_volume }}:/var/{{ docker_volume }} {{ docker_image_name }}

  - name: Change Jenkins-home ownership, group and permissions
    file:
      path: /home/{{ ansible_user }}/{{ docker_volume }}
      mode: "1755"
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      recurse: yes

...
