---

  - name: "Allow all access to tcp port {{ jenkins_port }}"
    firewalld:
      port: "{{ jenkins_port }}/tcp"
      permanent: yes
      state: enabled
      zone: public

  - name: reload service firewalld
    systemd:
      name: firewalld
      state: reloaded

...
