---

  - name: Check Hostname
    command: hostname
    register: hname
    tags: always

  - debug: msg="{{ hname.stdout }}"
    tags: always

  - import_tasks: install_jenkins.yml
    tags: install-jenkins

  - import_tasks: configure_jenkins.yml
    tags: configure-jenkins

...
