vars:
nexus_version: latest
nexus_download_url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
nexus_download_dest: /tmp/nexus-{{nexus_version}}-unix.tar.gz
nexus_extracted_dir: /tmp/nexus_extracted_dir
nexus_dir: /usr/local/nexus
admin_password: 'password'
# vars file for nexus-role
